============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 10 items

doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py FFFFF           [ 50%]
doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py FFFFF           [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py:8: AssertionError: assert Decimal('1') == Decimal('0')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py:13: AssertionError: assert Decimal('2') == Decimal('1')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py:18: AssertionError: assert Decimal('-1') == Decimal('0')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py:23: AssertionError: assert Decimal('1') == Decimal('-1')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py:28: AssertionError: assert Decimal('0.5') == Decimal('1')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py:7: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py:12: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py:18: decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py:24: AssertionError: assert 33 <= 28
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py:28: decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
=========================== short test summary info ============================
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_1
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_2
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_3
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_4
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_5
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py::test_violation_of_decimal_Decimal_shift_1
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py::test_violation_of_decimal_Decimal_shift_2
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py::test_violation_of_decimal_Decimal_shift_3
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py::test_violation_of_decimal_Decimal_shift_4
FAILED doc_and_code/mutants_2/decimal.Decimal.shift/mutant_2.py::test_violation_of_decimal_Decimal_shift_5
============================== 10 failed in 5.08s ==============================
