============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 5 items

doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py FFFFF             [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py:6: exceptiongroup.ExceptionGroup: Hypothesis found 3 distinct failures. (3 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py:24: AssertionError: assert Decimal('NaN') == Decimal('0')
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py:32: exceptiongroup.ExceptionGroup: Hypothesis found 3 distinct failures. (3 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py:45: exceptiongroup.ExceptionGroup: Hypothesis found 3 distinct failures. (3 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py:63: AssertionError: assert Decimal('NaN') == Decimal('0.0')
=========================== short test summary info ============================
FAILED doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py::test_violation_of_decimal_Decimal_fma_1
FAILED doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py::test_violation_of_decimal_Decimal_fma_2
FAILED doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py::test_violation_of_decimal_Decimal_fma_3
FAILED doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py::test_violation_of_decimal_Decimal_fma_4
FAILED doc_and_code/mutants_2/decimal.Decimal.fma/mutant_1.py::test_violation_of_decimal_Decimal_fma_5
============================== 5 failed in 7.72s ===============================
