============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 25 items

doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_1.py F.. [ 12%]
..                                                                       [ 20%]
doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py FFF [ 32%]
FF                                                                       [ 40%]
doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_3.py .F. [ 52%]
.F                                                                       [ 60%]
doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_4.py ... [ 72%]
.F                                                                       [ 80%]
doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py FFF [ 92%]
F.                                                                       [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_1.py:13: assert 0 > 0
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py:14: assert 0 == 1
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py:26: assert 0 == 1
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py:38: IndexError: list index out of range
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py:50: assert 1 == 0
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py:62: assert 0 == 2
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_3.py:22: assert (0, 0) not in OutEdgeView([(0, 0)])
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_3.py:52: assert ((0, 0) in OutEdgeView([(0, 0)]) and (0, 0) not in OutEdgeView([(0, 0)]))
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_4.py:52: assert (0, 0) not in OutEdgeView([(0, 0)])
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py:12: ValueError: too many values to unpack (expected 2)
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py:23: ValueError: too many values to unpack (expected 2)
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py:35: AssertionError: assert 'forward' == 'unknown'
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py:46: AssertionError: assert 'forward' not in ['forward', 'reverse']
=========================== short test summary info ============================
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_1.py::test_violation_of_networkx_algorithms_cycles_find_cycle_1
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py::test_violation_of_networkx_algorithms_cycles_find_cycle_1
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py::test_violation_of_networkx_algorithms_cycles_find_cycle_2
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py::test_violation_of_networkx_algorithms_cycles_find_cycle_3
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py::test_violation_of_networkx_algorithms_cycles_find_cycle_4
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_2.py::test_violation_of_networkx_algorithms_cycles_find_cycle_5
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_3.py::test_violation_of_networkx_algorithms_cycles_find_cycle_2
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_3.py::test_violation_of_networkx_algorithms_cycles_find_cycle_5
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_4.py::test_violation_of_networkx_algorithms_cycles_find_cycle_5
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py::test_violation_of_networkx_algorithms_cycles_find_cycle_1
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py::test_violation_of_networkx_algorithms_cycles_find_cycle_2
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py::test_violation_of_networkx_algorithms_cycles_find_cycle_3
FAILED doc_only/mutants_2/networkx.algorithms.cycles.find_cycle/mutant_5.py::test_violation_of_networkx_algorithms_cycles_find_cycle_4
======================== 13 failed, 12 passed in 2.29s =========================
