============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 15 items / 1 error

doc_only/mutants/decimal.Decimal.adjusted/mutant_1.py .F...              [ 33%]
doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py ..FFF              [ 66%]
doc_only/mutants/decimal.Decimal.adjusted/mutant_4.py ..F..              [100%]

==================================== ERRORS ====================================
____ ERROR collecting doc_only/mutants/decimal.Decimal.adjusted/mutant_3.py ____
E   TypeError: decimals() got an unexpected keyword argument 'allow_infinite'
=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants/decimal.Decimal.adjusted/mutant_1.py:15: AssertionError: assert 0 >= (0 + 1)
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py:27: AssertionError: assert 0 < -1
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py:35: AssertionError: assert -10 > -10
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py:43: AssertionError: assert 0 > 0
/home/james/projects/cs6223/our_proptest_data/doc_only/mutants/decimal.Decimal.adjusted/mutant_4.py:24: AssertionError: assert 0 != 0
=========================== short test summary info ============================
FAILED doc_only/mutants/decimal.Decimal.adjusted/mutant_1.py::test_violation_of_decimal_Decimal_adjusted_2
FAILED doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py::test_violation_of_decimal_Decimal_adjusted_3
FAILED doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py::test_violation_of_decimal_Decimal_adjusted_4
FAILED doc_only/mutants/decimal.Decimal.adjusted/mutant_2.py::test_violation_of_decimal_Decimal_adjusted_5
FAILED doc_only/mutants/decimal.Decimal.adjusted/mutant_4.py::test_violation_of_decimal_Decimal_adjusted_3
ERROR doc_only/mutants/decimal.Decimal.adjusted/mutant_3.py - TypeError: deci...
==================== 5 failed, 10 passed, 1 error in 1.33s =====================
