============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 5 items

code_only/mutants/decimal.Decimal.shift/mutant_1.py FFFFF                [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/code_only/mutants/decimal.Decimal.shift/mutant_1.py:6: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/code_only/mutants/decimal.Decimal.shift/mutant_1.py:13: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/code_only/mutants/decimal.Decimal.shift/mutant_1.py:20: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/code_only/mutants/decimal.Decimal.shift/mutant_1.py:27: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/code_only/mutants/decimal.Decimal.shift/mutant_1.py:34: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
=========================== short test summary info ============================
FAILED code_only/mutants/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_1
FAILED code_only/mutants/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_2
FAILED code_only/mutants/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_3
FAILED code_only/mutants/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_4
FAILED code_only/mutants/decimal.Decimal.shift/mutant_1.py::test_violation_of_decimal_Decimal_shift_5
============================== 5 failed in 20.05s ==============================
